site_name: OQLF practice
site_description: Bilingual EN/FR practice notes for OQLF case studies, French writing, and other resources.
site_url: https://janetlongxj.github.io/oqlf-practice/
repo_name: janetlongxj/oqlf-practice
repo_url: https://github.com/janetlongxj/oqlf-practice

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: white
      accent: blue grey
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home / Accueil: index.md
  
nav:
  - Case / Cas: case/index.md
  - French / Français: french/index.md
  - Other / Autres: other/index.md

copyright: Copyright &copy; 2026 OQLF practice

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com
      name: LinkedIn
    - icon: fontawesome/brands/googlescholar
      link: https://instagram.com
      name: Google scholar
